services:
  # Aplicación completa (Backend + Frontend)
  - type: web
    name: brumario-app
    env: node
    plan: free
    buildCommand: npm run install:all && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://ncarreno_db_user:Kj0CEGNVXNyFT8Zi@brumario.exqorlm.mongodb.net/?appName=brumario
      - key: PORT
        value: 10000
    healthCheckPath: /api/hello