services:
  - type: web
    name: brumario
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run build_prod
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://ncarreno_db_user:Kj0CEGNVXNyFT8Zi@brumario.exqorlm.mongodb.net/?appName=brumario
    healthCheckPath: /hello
